app_config:
  package_name: my_model 
  pipeline_name: my_model_pipeline
  pipeline_save_file: my_model_pipeline_draft
  train_data_file: train.csv
  test_data_file: test.csv


transformer_config:
  features_to_skip:
    - name 
    - passenger_id
    - cabin
    - age
    - ticket
  features_to_impute:
    - embarked
    - sex
    - sib_sp
    - parch
  features_to_encode:
    - sex
    - embarked

model_config:
  n_estimators: 150
  max_depth: 5
  random_state: 42

  
data_config:
  rename_columns:
    PassengerId: passenger_id
    Pclass: p_class
    Age: age
    SibSp: sib_sp
    Parch: parch
    Fare: fare
    Name: name
    Sex: sex
    Ticket: ticket
    Cabin: cabin
    Embarked: embarked
  features:
    - passenger_id
    - p_class
    - age
    - sib_sp
    - parch
    - fare
    - name
    - sex
    - ticket
    - cabin
    - embarked
  target: Survived

